stages:
  - build
  - deploy

build-prod:
  stage: build
  only:
    - main
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:prod-latest -f ./Dockerfile .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:prod-latest
    - docker system prune -a -f
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

deploy-prod:
  stage: deploy
  only:
    - main
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:prod-latest
    - docker-compose up -d
    - docker system prune -a -f
