version: '3'
services:
  app:
    build:
      context: ./
    ports:
      - "8080:8080" 
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # Gantilah path sesuai dengan lokasi file nginx.conf Anda
    depends_on:
      - app
