version: '3'
services:
  backend:
    container_name: rockmaker-backend
    restart: unless-stopped
    build:
      context: ./
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - "8000:8000" 
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # Gantilah path sesuai dengan lokasi file nginx.conf Anda
    depends_on:
      - backend
